import { reducer as formReducer } from 'redux-form';
import { combineReducers } from 'redux';

const rootReducer = combineReducers({
  // `formReducer` is a reducer provided by `redux-form`.
  // It processes actions generated by `<Field />` components.
  //
  form: formReducer
});

export default rootReducer;